spring:
  data:
    mongodb:
      auto-index-creation: true
      host: mongodb
      port: 27017
  graphql:
    cors:
      allowed-origins: "*"
    graphiql:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
