version: '3.8'
services:
  mongodb:
    build: mongodb
    container_name: conjugaison-mongodb
    restart: always
    expose:
      - '27017'
  api:
    container_name: conjugaison-api
    build: .
    image: conjugaison-service
    depends_on:
      - mongodb
    ports:
      - '8080:8080'    # GraphQL API
    links:
      - mongodb
